apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cr2alkg6v-python
  janus-idp.io/tekton: cr2alkg6v-python
  backstage.io/kubernetes-id: cr2alkg6v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cr2alkg6v-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
